version: "3.8"

services:
  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "8081:8081"
    depends_on:
      - user_service
      - food_service
    environment:
      USER_SERVICE_URL: http://user_service:5002
      FOOD_SERVICE_URL: http://food_service:5001

  user_service:
    build:
      context: ./apps/user-service
    ports:
      - "5002:5002"
    environment:
      MONGO_URI: "mongodb+srv://mashawijesekara:7HO4hnI0D9CDyJOw@cluster0.tjxwt5d.mongodb.net/userService_cakeshop"
      PORT: 5002
      JWT_SECRET: "AbholkcnjklHuexw496434178@897"

  food_service:
    build:
      context: ./apps/food-service
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: "mongodb+srv://mashawijesekara:7HO4hnI0D9CDyJOw@cluster0.tjxwt5d.mongodb.net/foodService_cakeshop"
      PORT: 5001
