apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-svc
  template:
    metadata:
      labels:
        app: frontend-svc
    spec:
      containers:
      - name: frontend-svc
        image: masha230/frontend
        ports:
        - containerPort: 3000  # Common React app port, change if needed
        env:
        - name: NODE_ENV
          value: "production"
        - name: REACT_APP_CART_SERVICE_URL
          value: "http://cart-svc:5003"
        - name: API_GATEWAY_URL
          value: "http://api-gateway:8081"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  selector:
    app: frontend-svc
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30011
