apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env
data:
  env.js: |
    window._env_ = {
      API_GATEWAY_URL: "http://api-gateway:8081",
      CART_SERVICE_URL: "http://cart-svc:5003"
    };
