apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-svc
  template:
    metadata:
      labels:
        app: notification-svc
    spec:
      containers:
      - name: notification-svc
        image: masha230/notification-service
        ports:
        - containerPort: 5005
        env:
        - name: RABBITMQ_URL
          value: amqp://rabbitmq:5672
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: notification-svc-secrets
              key: SENDGRID_API_KEY
        - name: SENDGRID_FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: notification-svc-secrets
              key: SENDGRID_FROM_EMAIL
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
              secretKeyRef:
                name: notification-svc-secrets
                key: TWILIO_ACCOUNT_SID
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: notification-svc-secrets
              key: TWILIO_AUTH_TOKEN
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: notification-svc-secrets
              key: TWILIO_PHONE_NUMBER
        - name: PORT
          value: "5005"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-svc
spec:
  type: ClusterIP
  selector:
    app: notification-svc
  ports:
    - port: 5005
