apiVersion: batch/v1
kind: Job
metadata:
  name: order-migrate
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: masha230/order-service
        command: ["npx", "prisma", "migrate", "deploy"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: order-svc-secrets
              key: DATABASE_URL
      restartPolicy: Never
