apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-svc
  template:
    metadata:
      labels:
        app: order-svc
    spec:
      containers:
      - name: order-svc
        image: masha230/order-service
        ports:
        - containerPort: 5004
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: order-svc-secrets
              key: DATABASE_URL
        - name: RABBITMQ_URL
          value: amqp://rabbitmq:5672
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  type: NordPort
  selector:
    app: order-svc
  ports:
    - port: 5004
    targetPort:5004
    nodePort:30004
