apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
  labels:
    app: rabbitmq-consumer
spec:
  replicas: 1 # increase if you want multiple workers
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z rabbitmq 5672; do
                echo "waiting for rabbitmq"
                sleep 5
              done
      containers:
        - name: rabbitmq-consumer
          image: masha230/rabbitmqconsumer-service
          env:
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672
            - name: NOTIFICATION_SERVICE_URL
              value: http://notification-svc:5005/api/notifications
            - name: ENABLE_HEALTH_CHECK
              value: "true"
            - name: HEALTH_CHECK_PORT
              value: "5010"
            - name: NODE_ENV
              value: development
          ports:
            - containerPort: 5010
          livenessProbe:   # ✅ optional but recommended
            httpGet:
              path: /health
              port: 5010
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:  # ✅ makes sure pod is "ready" before traffic
            httpGet:
              path: /health
              port: 5010
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-consumer
spec:
  selector:
    app: rabbitmq-consumer
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 5010
  type: ClusterIP
