apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      containers:
      - name: user-svc
        image: user-service:latest  # ← CHANGE TO LOCAL IMAGE NAME
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
        env:
        - name: MONGO_URI_USER
          valueFrom:
            secretKeyRef:
              name: user-svc-secrets
              key: MONGO_URI_USER
        - name: PORT
          value: "5002"
        - name: JWT_SECRET_USER
          valueFrom:
            secretKeyRef:
              name: user-svc-secrets
              key: JWT_SECRET_USER
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  annotations:  # ← PROMETHEUS ANNOTATIONS ADDED HERE
    prometheus.io/scrape: "true"
    prometheus.io/port: "5002"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector:
    app: user-svc
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30002
