apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      containers:
      - name: user-svc
        image: masha230/user-service
        ports:
        - containerPort: 5002
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: user-svc-secrets
              key: MONGO_URI
        - name: PORT
          value: "5002"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: user-svc-secrets
              key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  type: ClusterIP
  selector:
    app: user-svc
  ports:
    - port: 5002
